### ISSUE TITLE
How do I use this? Does it work for .flac files?

### ISSUE THREAD

**Issue by dessalines** [cruxic/jvorbiscomment#2]
Could you provide more info on how to use this in your readme?

**Comment by cruxic** [comment]
Good point.  I just added some examples from the javadocs to the project README.  That should get you started.  Detailed javadocs are in the release zip (see "releases").

Regarding .flac files.  It might work, you'll just have to try it (backup your file first!).  Tell me how it goes.  The library was written and tested against Ogg-Vorbis files.  I won't claim FLAC support until the test-suite has coverage for FLAC files.

**Comment by dessalines** [comment]
@cruxic Thanks a ton, looks pretty good. You might want to also provide a maven URL to make it usable.
